#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFTestV5
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Pathfinder")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBASE_CLASS(BASE_CLASS instance);
    partial void UpdateBASE_CLASS(BASE_CLASS instance);
    partial void DeleteBASE_CLASS(BASE_CLASS instance);
    partial void InsertRACE(RACE instance);
    partial void UpdateRACE(RACE instance);
    partial void DeleteRACE(RACE instance);
    partial void InsertWEAPON(WEAPON instance);
    partial void UpdateWEAPON(WEAPON instance);
    partial void DeleteWEAPON(WEAPON instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::PFTestV5.Properties.Settings.Default.PathfinderConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BASE_CLASS> BASE_CLASSes
		{
			get
			{
				return this.GetTable<BASE_CLASS>();
			}
		}
		
		public System.Data.Linq.Table<RACE> RACEs
		{
			get
			{
				return this.GetTable<RACE>();
			}
		}
		
		public System.Data.Linq.Table<WEAPON> WEAPONs
		{
			get
			{
				return this.GetTable<WEAPON>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BASE_CLASS")]
	public partial class BASE_CLASS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CLASS_ID;
		
		private string _CLASS_NAME;
		
		private int _CLASS_HITDIE;
		
		private decimal _CLASS_BAB_PROGRESSION;
		
		private decimal _CLASS_FORT_PROGRESSION;
		
		private decimal _CLASS_REF_PROGRESSION;
		
		private decimal _CLASS_WILL_PROGRESSION;
		
		private int _CLASS_SKILL_RANK_MOD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCLASS_IDChanging(int value);
    partial void OnCLASS_IDChanged();
    partial void OnCLASS_NAMEChanging(string value);
    partial void OnCLASS_NAMEChanged();
    partial void OnCLASS_HITDIEChanging(int value);
    partial void OnCLASS_HITDIEChanged();
    partial void OnCLASS_BAB_PROGRESSIONChanging(decimal value);
    partial void OnCLASS_BAB_PROGRESSIONChanged();
    partial void OnCLASS_FORT_PROGRESSIONChanging(decimal value);
    partial void OnCLASS_FORT_PROGRESSIONChanged();
    partial void OnCLASS_REF_PROGRESSIONChanging(decimal value);
    partial void OnCLASS_REF_PROGRESSIONChanged();
    partial void OnCLASS_WILL_PROGRESSIONChanging(decimal value);
    partial void OnCLASS_WILL_PROGRESSIONChanged();
    partial void OnCLASS_SKILL_RANK_MODChanging(int value);
    partial void OnCLASS_SKILL_RANK_MODChanged();
    #endregion
		
		public BASE_CLASS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CLASS_ID
		{
			get
			{
				return this._CLASS_ID;
			}
			set
			{
				if ((this._CLASS_ID != value))
				{
					this.OnCLASS_IDChanging(value);
					this.SendPropertyChanging();
					this._CLASS_ID = value;
					this.SendPropertyChanged("CLASS_ID");
					this.OnCLASS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_NAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string CLASS_NAME
		{
			get
			{
				return this._CLASS_NAME;
			}
			set
			{
				if ((this._CLASS_NAME != value))
				{
					this.OnCLASS_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CLASS_NAME = value;
					this.SendPropertyChanged("CLASS_NAME");
					this.OnCLASS_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_HITDIE", DbType="Int NOT NULL")]
		public int CLASS_HITDIE
		{
			get
			{
				return this._CLASS_HITDIE;
			}
			set
			{
				if ((this._CLASS_HITDIE != value))
				{
					this.OnCLASS_HITDIEChanging(value);
					this.SendPropertyChanging();
					this._CLASS_HITDIE = value;
					this.SendPropertyChanged("CLASS_HITDIE");
					this.OnCLASS_HITDIEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_BAB_PROGRESSION", DbType="Decimal(18,0) NOT NULL")]
		public decimal CLASS_BAB_PROGRESSION
		{
			get
			{
				return this._CLASS_BAB_PROGRESSION;
			}
			set
			{
				if ((this._CLASS_BAB_PROGRESSION != value))
				{
					this.OnCLASS_BAB_PROGRESSIONChanging(value);
					this.SendPropertyChanging();
					this._CLASS_BAB_PROGRESSION = value;
					this.SendPropertyChanged("CLASS_BAB_PROGRESSION");
					this.OnCLASS_BAB_PROGRESSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_FORT_PROGRESSION", DbType="Decimal(18,0) NOT NULL")]
		public decimal CLASS_FORT_PROGRESSION
		{
			get
			{
				return this._CLASS_FORT_PROGRESSION;
			}
			set
			{
				if ((this._CLASS_FORT_PROGRESSION != value))
				{
					this.OnCLASS_FORT_PROGRESSIONChanging(value);
					this.SendPropertyChanging();
					this._CLASS_FORT_PROGRESSION = value;
					this.SendPropertyChanged("CLASS_FORT_PROGRESSION");
					this.OnCLASS_FORT_PROGRESSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_REF_PROGRESSION", DbType="Decimal(18,0) NOT NULL")]
		public decimal CLASS_REF_PROGRESSION
		{
			get
			{
				return this._CLASS_REF_PROGRESSION;
			}
			set
			{
				if ((this._CLASS_REF_PROGRESSION != value))
				{
					this.OnCLASS_REF_PROGRESSIONChanging(value);
					this.SendPropertyChanging();
					this._CLASS_REF_PROGRESSION = value;
					this.SendPropertyChanged("CLASS_REF_PROGRESSION");
					this.OnCLASS_REF_PROGRESSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_WILL_PROGRESSION", DbType="Decimal(18,0) NOT NULL")]
		public decimal CLASS_WILL_PROGRESSION
		{
			get
			{
				return this._CLASS_WILL_PROGRESSION;
			}
			set
			{
				if ((this._CLASS_WILL_PROGRESSION != value))
				{
					this.OnCLASS_WILL_PROGRESSIONChanging(value);
					this.SendPropertyChanging();
					this._CLASS_WILL_PROGRESSION = value;
					this.SendPropertyChanged("CLASS_WILL_PROGRESSION");
					this.OnCLASS_WILL_PROGRESSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_SKILL_RANK_MOD", DbType="Int NOT NULL")]
		public int CLASS_SKILL_RANK_MOD
		{
			get
			{
				return this._CLASS_SKILL_RANK_MOD;
			}
			set
			{
				if ((this._CLASS_SKILL_RANK_MOD != value))
				{
					this.OnCLASS_SKILL_RANK_MODChanging(value);
					this.SendPropertyChanging();
					this._CLASS_SKILL_RANK_MOD = value;
					this.SendPropertyChanged("CLASS_SKILL_RANK_MOD");
					this.OnCLASS_SKILL_RANK_MODChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RACE")]
	public partial class RACE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RACE_ID;
		
		private string _RACE_NAME;
		
		private int _RACE_STR;
		
		private int _RACE_DEX;
		
		private int _RACE_CON;
		
		private int _RACE_INT;
		
		private int _RACE_WIS;
		
		private int _RACE_CHA;
		
		private int _RACE_SIZE_MOD;
		
		private string _RACE_TYPE;
		
		private string _RACE_SUBTYPE;
		
		private int _RACE_SPEED;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRACE_IDChanging(int value);
    partial void OnRACE_IDChanged();
    partial void OnRACE_NAMEChanging(string value);
    partial void OnRACE_NAMEChanged();
    partial void OnRACE_STRChanging(int value);
    partial void OnRACE_STRChanged();
    partial void OnRACE_DEXChanging(int value);
    partial void OnRACE_DEXChanged();
    partial void OnRACE_CONChanging(int value);
    partial void OnRACE_CONChanged();
    partial void OnRACE_INTChanging(int value);
    partial void OnRACE_INTChanged();
    partial void OnRACE_WISChanging(int value);
    partial void OnRACE_WISChanged();
    partial void OnRACE_CHAChanging(int value);
    partial void OnRACE_CHAChanged();
    partial void OnRACE_SIZE_MODChanging(int value);
    partial void OnRACE_SIZE_MODChanged();
    partial void OnRACE_TYPEChanging(string value);
    partial void OnRACE_TYPEChanged();
    partial void OnRACE_SUBTYPEChanging(string value);
    partial void OnRACE_SUBTYPEChanged();
    partial void OnRACE_SPEEDChanging(int value);
    partial void OnRACE_SPEEDChanged();
    #endregion
		
		public RACE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RACE_ID
		{
			get
			{
				return this._RACE_ID;
			}
			set
			{
				if ((this._RACE_ID != value))
				{
					this.OnRACE_IDChanging(value);
					this.SendPropertyChanging();
					this._RACE_ID = value;
					this.SendPropertyChanged("RACE_ID");
					this.OnRACE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE_NAME", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RACE_NAME
		{
			get
			{
				return this._RACE_NAME;
			}
			set
			{
				if ((this._RACE_NAME != value))
				{
					this.OnRACE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._RACE_NAME = value;
					this.SendPropertyChanged("RACE_NAME");
					this.OnRACE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE_STR", DbType="Int NOT NULL")]
		public int RACE_STR
		{
			get
			{
				return this._RACE_STR;
			}
			set
			{
				if ((this._RACE_STR != value))
				{
					this.OnRACE_STRChanging(value);
					this.SendPropertyChanging();
					this._RACE_STR = value;
					this.SendPropertyChanged("RACE_STR");
					this.OnRACE_STRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE_DEX", DbType="Int NOT NULL")]
		public int RACE_DEX
		{
			get
			{
				return this._RACE_DEX;
			}
			set
			{
				if ((this._RACE_DEX != value))
				{
					this.OnRACE_DEXChanging(value);
					this.SendPropertyChanging();
					this._RACE_DEX = value;
					this.SendPropertyChanged("RACE_DEX");
					this.OnRACE_DEXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE_CON", DbType="Int NOT NULL")]
		public int RACE_CON
		{
			get
			{
				return this._RACE_CON;
			}
			set
			{
				if ((this._RACE_CON != value))
				{
					this.OnRACE_CONChanging(value);
					this.SendPropertyChanging();
					this._RACE_CON = value;
					this.SendPropertyChanged("RACE_CON");
					this.OnRACE_CONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE_INT", DbType="Int NOT NULL")]
		public int RACE_INT
		{
			get
			{
				return this._RACE_INT;
			}
			set
			{
				if ((this._RACE_INT != value))
				{
					this.OnRACE_INTChanging(value);
					this.SendPropertyChanging();
					this._RACE_INT = value;
					this.SendPropertyChanged("RACE_INT");
					this.OnRACE_INTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE_WIS", DbType="Int NOT NULL")]
		public int RACE_WIS
		{
			get
			{
				return this._RACE_WIS;
			}
			set
			{
				if ((this._RACE_WIS != value))
				{
					this.OnRACE_WISChanging(value);
					this.SendPropertyChanging();
					this._RACE_WIS = value;
					this.SendPropertyChanged("RACE_WIS");
					this.OnRACE_WISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE_CHA", DbType="Int NOT NULL")]
		public int RACE_CHA
		{
			get
			{
				return this._RACE_CHA;
			}
			set
			{
				if ((this._RACE_CHA != value))
				{
					this.OnRACE_CHAChanging(value);
					this.SendPropertyChanging();
					this._RACE_CHA = value;
					this.SendPropertyChanged("RACE_CHA");
					this.OnRACE_CHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE_SIZE_MOD", DbType="Int NOT NULL")]
		public int RACE_SIZE_MOD
		{
			get
			{
				return this._RACE_SIZE_MOD;
			}
			set
			{
				if ((this._RACE_SIZE_MOD != value))
				{
					this.OnRACE_SIZE_MODChanging(value);
					this.SendPropertyChanging();
					this._RACE_SIZE_MOD = value;
					this.SendPropertyChanged("RACE_SIZE_MOD");
					this.OnRACE_SIZE_MODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE_TYPE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RACE_TYPE
		{
			get
			{
				return this._RACE_TYPE;
			}
			set
			{
				if ((this._RACE_TYPE != value))
				{
					this.OnRACE_TYPEChanging(value);
					this.SendPropertyChanging();
					this._RACE_TYPE = value;
					this.SendPropertyChanged("RACE_TYPE");
					this.OnRACE_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE_SUBTYPE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RACE_SUBTYPE
		{
			get
			{
				return this._RACE_SUBTYPE;
			}
			set
			{
				if ((this._RACE_SUBTYPE != value))
				{
					this.OnRACE_SUBTYPEChanging(value);
					this.SendPropertyChanging();
					this._RACE_SUBTYPE = value;
					this.SendPropertyChanged("RACE_SUBTYPE");
					this.OnRACE_SUBTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE_SPEED", DbType="Int NOT NULL")]
		public int RACE_SPEED
		{
			get
			{
				return this._RACE_SPEED;
			}
			set
			{
				if ((this._RACE_SPEED != value))
				{
					this.OnRACE_SPEEDChanging(value);
					this.SendPropertyChanging();
					this._RACE_SPEED = value;
					this.SendPropertyChanged("RACE_SPEED");
					this.OnRACE_SPEEDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WEAPON")]
	public partial class WEAPON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _WEAPON_ID;
		
		private string _WEAPON_NAME;
		
		private int _WEAPON_DAMAGE_DIE_COUNT;
		
		private int _WEAPON_DAMAGE_DIE_SIZE;
		
		private int _WEAPON_CRIT_RANGE;
		
		private int _WEAPON_CRIT_MODIFIER;
		
		private string _WEAPON_DAMAGE_TYPE;
		
		private int _WEAPON_CATAGORY;
		
		private int _WEAPON_PROFICIENCY_TYPE;
		
		private int _WEAPON_GROUP_KEY;
		
		private int _WEAPON_COST;
		
		private int _WEAPON_WEIGHT;
		
		private bool _WEAPON_REACH_FLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWEAPON_IDChanging(int value);
    partial void OnWEAPON_IDChanged();
    partial void OnWEAPON_NAMEChanging(string value);
    partial void OnWEAPON_NAMEChanged();
    partial void OnWEAPON_DAMAGE_DIE_COUNTChanging(int value);
    partial void OnWEAPON_DAMAGE_DIE_COUNTChanged();
    partial void OnWEAPON_DAMAGE_DIE_SIZEChanging(int value);
    partial void OnWEAPON_DAMAGE_DIE_SIZEChanged();
    partial void OnWEAPON_CRIT_RANGEChanging(int value);
    partial void OnWEAPON_CRIT_RANGEChanged();
    partial void OnWEAPON_CRIT_MODIFIERChanging(int value);
    partial void OnWEAPON_CRIT_MODIFIERChanged();
    partial void OnWEAPON_DAMAGE_TYPEChanging(string value);
    partial void OnWEAPON_DAMAGE_TYPEChanged();
    partial void OnWEAPON_CATAGORYChanging(int value);
    partial void OnWEAPON_CATAGORYChanged();
    partial void OnWEAPON_PROFICIENCY_TYPEChanging(int value);
    partial void OnWEAPON_PROFICIENCY_TYPEChanged();
    partial void OnWEAPON_GROUP_KEYChanging(int value);
    partial void OnWEAPON_GROUP_KEYChanged();
    partial void OnWEAPON_COSTChanging(int value);
    partial void OnWEAPON_COSTChanged();
    partial void OnWEAPON_WEIGHTChanging(int value);
    partial void OnWEAPON_WEIGHTChanged();
    partial void OnWEAPON_REACH_FLAGChanging(bool value);
    partial void OnWEAPON_REACH_FLAGChanged();
    #endregion
		
		public WEAPON()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEAPON_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int WEAPON_ID
		{
			get
			{
				return this._WEAPON_ID;
			}
			set
			{
				if ((this._WEAPON_ID != value))
				{
					this.OnWEAPON_IDChanging(value);
					this.SendPropertyChanging();
					this._WEAPON_ID = value;
					this.SendPropertyChanged("WEAPON_ID");
					this.OnWEAPON_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEAPON_NAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string WEAPON_NAME
		{
			get
			{
				return this._WEAPON_NAME;
			}
			set
			{
				if ((this._WEAPON_NAME != value))
				{
					this.OnWEAPON_NAMEChanging(value);
					this.SendPropertyChanging();
					this._WEAPON_NAME = value;
					this.SendPropertyChanged("WEAPON_NAME");
					this.OnWEAPON_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEAPON_DAMAGE_DIE_COUNT", DbType="Int NOT NULL")]
		public int WEAPON_DAMAGE_DIE_COUNT
		{
			get
			{
				return this._WEAPON_DAMAGE_DIE_COUNT;
			}
			set
			{
				if ((this._WEAPON_DAMAGE_DIE_COUNT != value))
				{
					this.OnWEAPON_DAMAGE_DIE_COUNTChanging(value);
					this.SendPropertyChanging();
					this._WEAPON_DAMAGE_DIE_COUNT = value;
					this.SendPropertyChanged("WEAPON_DAMAGE_DIE_COUNT");
					this.OnWEAPON_DAMAGE_DIE_COUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEAPON_DAMAGE_DIE_SIZE", DbType="Int NOT NULL")]
		public int WEAPON_DAMAGE_DIE_SIZE
		{
			get
			{
				return this._WEAPON_DAMAGE_DIE_SIZE;
			}
			set
			{
				if ((this._WEAPON_DAMAGE_DIE_SIZE != value))
				{
					this.OnWEAPON_DAMAGE_DIE_SIZEChanging(value);
					this.SendPropertyChanging();
					this._WEAPON_DAMAGE_DIE_SIZE = value;
					this.SendPropertyChanged("WEAPON_DAMAGE_DIE_SIZE");
					this.OnWEAPON_DAMAGE_DIE_SIZEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEAPON_CRIT_RANGE", DbType="Int NOT NULL")]
		public int WEAPON_CRIT_RANGE
		{
			get
			{
				return this._WEAPON_CRIT_RANGE;
			}
			set
			{
				if ((this._WEAPON_CRIT_RANGE != value))
				{
					this.OnWEAPON_CRIT_RANGEChanging(value);
					this.SendPropertyChanging();
					this._WEAPON_CRIT_RANGE = value;
					this.SendPropertyChanged("WEAPON_CRIT_RANGE");
					this.OnWEAPON_CRIT_RANGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEAPON_CRIT_MODIFIER", DbType="Int NOT NULL")]
		public int WEAPON_CRIT_MODIFIER
		{
			get
			{
				return this._WEAPON_CRIT_MODIFIER;
			}
			set
			{
				if ((this._WEAPON_CRIT_MODIFIER != value))
				{
					this.OnWEAPON_CRIT_MODIFIERChanging(value);
					this.SendPropertyChanging();
					this._WEAPON_CRIT_MODIFIER = value;
					this.SendPropertyChanged("WEAPON_CRIT_MODIFIER");
					this.OnWEAPON_CRIT_MODIFIERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEAPON_DAMAGE_TYPE", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string WEAPON_DAMAGE_TYPE
		{
			get
			{
				return this._WEAPON_DAMAGE_TYPE;
			}
			set
			{
				if ((this._WEAPON_DAMAGE_TYPE != value))
				{
					this.OnWEAPON_DAMAGE_TYPEChanging(value);
					this.SendPropertyChanging();
					this._WEAPON_DAMAGE_TYPE = value;
					this.SendPropertyChanged("WEAPON_DAMAGE_TYPE");
					this.OnWEAPON_DAMAGE_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEAPON_CATAGORY", DbType="Int NOT NULL")]
		public int WEAPON_CATAGORY
		{
			get
			{
				return this._WEAPON_CATAGORY;
			}
			set
			{
				if ((this._WEAPON_CATAGORY != value))
				{
					this.OnWEAPON_CATAGORYChanging(value);
					this.SendPropertyChanging();
					this._WEAPON_CATAGORY = value;
					this.SendPropertyChanged("WEAPON_CATAGORY");
					this.OnWEAPON_CATAGORYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEAPON_PROFICIENCY_TYPE", DbType="Int NOT NULL")]
		public int WEAPON_PROFICIENCY_TYPE
		{
			get
			{
				return this._WEAPON_PROFICIENCY_TYPE;
			}
			set
			{
				if ((this._WEAPON_PROFICIENCY_TYPE != value))
				{
					this.OnWEAPON_PROFICIENCY_TYPEChanging(value);
					this.SendPropertyChanging();
					this._WEAPON_PROFICIENCY_TYPE = value;
					this.SendPropertyChanged("WEAPON_PROFICIENCY_TYPE");
					this.OnWEAPON_PROFICIENCY_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEAPON_GROUP_KEY", DbType="Int NOT NULL")]
		public int WEAPON_GROUP_KEY
		{
			get
			{
				return this._WEAPON_GROUP_KEY;
			}
			set
			{
				if ((this._WEAPON_GROUP_KEY != value))
				{
					this.OnWEAPON_GROUP_KEYChanging(value);
					this.SendPropertyChanging();
					this._WEAPON_GROUP_KEY = value;
					this.SendPropertyChanged("WEAPON_GROUP_KEY");
					this.OnWEAPON_GROUP_KEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEAPON_COST", DbType="Int NOT NULL")]
		public int WEAPON_COST
		{
			get
			{
				return this._WEAPON_COST;
			}
			set
			{
				if ((this._WEAPON_COST != value))
				{
					this.OnWEAPON_COSTChanging(value);
					this.SendPropertyChanging();
					this._WEAPON_COST = value;
					this.SendPropertyChanged("WEAPON_COST");
					this.OnWEAPON_COSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEAPON_WEIGHT", DbType="Int NOT NULL")]
		public int WEAPON_WEIGHT
		{
			get
			{
				return this._WEAPON_WEIGHT;
			}
			set
			{
				if ((this._WEAPON_WEIGHT != value))
				{
					this.OnWEAPON_WEIGHTChanging(value);
					this.SendPropertyChanging();
					this._WEAPON_WEIGHT = value;
					this.SendPropertyChanged("WEAPON_WEIGHT");
					this.OnWEAPON_WEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEAPON_REACH_FLAG", DbType="Bit NOT NULL")]
		public bool WEAPON_REACH_FLAG
		{
			get
			{
				return this._WEAPON_REACH_FLAG;
			}
			set
			{
				if ((this._WEAPON_REACH_FLAG != value))
				{
					this.OnWEAPON_REACH_FLAGChanging(value);
					this.SendPropertyChanging();
					this._WEAPON_REACH_FLAG = value;
					this.SendPropertyChanged("WEAPON_REACH_FLAG");
					this.OnWEAPON_REACH_FLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
